layout: sidebar
style: dark

#Adding heap assignment

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 15
  exclude:
    archived: false
    forks: true
    projects:
      - Dropbox-Assignment
      - Resume
      - Chess-Puzzles
      - CSS-HAML-Module2
      - VRx
      - coming-soon
      - CSE3311_Flutter
      - laspalmas
      - LowestRatedReview
      - XSauced_web
      - xSauced
      - Kaggle-notebooks
      - Heap-Assignment
      
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  #hackerrank: vishesh_gupta771
  linkedin: visheshgupta7
  instagram: vishesh79
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: thevisheshgupta
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # resume: Resume
  # youtube: your_username


topics:
  - name: Django 
    web_url: https://github.com/django/django
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/django/django.png

  - name: Unity
    web_url: https://github.com/topics/unity
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/unity/unity.png


  - name: Tensorflow
    web_url: https://github.com/topics/tensorflow
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/tensorflow/tensorflow.png

