layout: sidebar
style: dark

#Adding heap assignment

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: false
    forks: true
    projects:
      - Dropbox-Assignment
      - Resume
      - Chess-Puzzles
      - CSS-HAML-Module2
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  #hackerrank: vishesh_gupta771
  linkedin: visheshgupta9777
  instagram: vishesh79
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: vishesh7779
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  resume: Resume
  # youtube: your_username


topics:
  - name: Natural Language Processing   
    web_url: https://github.com/topics/nlp
    image_url: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/b2/8733c0b06511e7958c7f63f0f736f7/Natural-language-processing-2.png?auto=format%2Ccompress&dpr=2.625

  - name: Node.js 
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png


  - name: Tensorflow
    web_url: https://github.com/topics/tensorflow
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/tensorflow/tensorflow.png

